export const categories = [
  { id: "favorites", icon: "⭐", en: "Favorites", pa: "ਮਨਪਸੰਦ" },
  { id: "urgent", icon: "🆘", en: "Urgent", pa: "ਜ਼ਰੂਰੀ" },
  { id: "comfort", icon: "🛏️", en: "Comfort", pa: "ਆਰਾਮ" },
  { id: "body", icon: "🫶", en: "Body", pa: "ਸਰੀਰ" },
  { id: "food", icon: "🥣", en: "Food", pa: "ਖਾਣਾ" },
  { id: "care", icon: "🩺", en: "Care", pa: "ਦੇਖਭਾਲ" },
  { id: "activities", icon: "🎧", en: "More", pa: "ਹੋਰ" },
];

export const seedRequests = [
  {
    id: "nurse",
    category: "urgent",
    icon: "👩‍⚕️",
    en: "Call nurse",
    pa: "ਨਰਸ ਬੁਲਾਓ",
    speakEn: "Please call the nurse.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਨਰਸ ਨੂੰ ਬੁਲਾਓ।",
    favorite: true,
    visible: true,
    tone: "urgent",
  },
  {
    id: "help-now",
    category: "urgent",
    icon: "🆘",
    en: "Help now",
    pa: "ਹੁਣੇ ਮਦਦ",
    speakEn: "I need help right now.",
    speakPa: "ਮੈਨੂੰ ਹੁਣੇ ਮਦਦ ਚਾਹੀਦੀ ਹੈ।",
    favorite: true,
    visible: true,
    tone: "urgent",
  },
  {
    id: "breathing",
    category: "urgent",
    icon: "🫁",
    en: "Can't breathe",
    pa: "ਸਾਹ ਨਹੀਂ ਆ ਰਿਹਾ",
    speakEn: "I am having trouble breathing. Please help now.",
    speakPa: "ਮੈਨੂੰ ਸਾਹ ਲੈਣ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੋ ਰਹੀ ਹੈ। ਹੁਣੇ ਮਦਦ ਕਰੋ।",
    favorite: false,
    visible: true,
    tone: "urgent",
  },
  {
    id: "pain",
    category: "body",
    icon: "🤕",
    en: "I am in pain",
    pa: "ਮੈਨੂੰ ਦਰਦ ਹੈ",
    speakEn: "I am in pain.",
    speakPa: "ਮੈਨੂੰ ਦਰਦ ਹੈ।",
    favorite: true,
    visible: true,
    tone: "pain",
    action: "pain",
  },
  {
    id: "yes",
    category: "favorites",
    icon: "👍",
    en: "Yes",
    pa: "ਹਾਂ",
    speakEn: "Yes.",
    speakPa: "ਹਾਂ।",
    favorite: true,
    visible: true,
    tone: "yes",
  },
  {
    id: "no",
    category: "favorites",
    icon: "👎",
    en: "No",
    pa: "ਨਹੀਂ",
    speakEn: "No.",
    speakPa: "ਨਹੀਂ।",
    favorite: true,
    visible: true,
    tone: "no",
  },
  {
    id: "water",
    category: "food",
    icon: "💧",
    en: "Water",
    pa: "ਪਾਣੀ",
    speakEn: "I would like some water.",
    speakPa: "ਮੈਨੂੰ ਪਾਣੀ ਚਾਹੀਦਾ ਹੈ।",
    favorite: true,
    visible: true,
  },
  {
    id: "hungry",
    category: "food",
    icon: "🥣",
    en: "I am hungry",
    pa: "ਮੈਨੂੰ ਭੁੱਖ ਲੱਗੀ ਹੈ",
    speakEn: "I am hungry. I would like something to eat.",
    speakPa: "ਮੈਨੂੰ ਭੁੱਖ ਲੱਗੀ ਹੈ। ਮੈਨੂੰ ਕੁਝ ਖਾਣ ਲਈ ਚਾਹੀਦਾ ਹੈ।",
    favorite: true,
    visible: true,
  },
  {
    id: "tea",
    category: "food",
    icon: "☕",
    en: "Tea",
    pa: "ਚਾਹ",
    speakEn: "I would like some tea.",
    speakPa: "ਮੈਨੂੰ ਚਾਹ ਚਾਹੀਦੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "change-me",
    category: "body",
    icon: "🧷",
    en: "Change me",
    pa: "ਮੈਨੂੰ ਬਦਲੋ",
    speakEn: "I need to be changed, please.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਬਦਲੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "poop",
    category: "body",
    icon: "🚽",
    en: "Need to poop",
    pa: "ਪਖਾਨਾ ਜਾਣਾ ਹੈ",
    speakEn: "I need to have a bowel movement.",
    speakPa: "ਮੈਨੂੰ ਪਖਾਨਾ ਜਾਣਾ ਹੈ।",
    favorite: true,
    visible: true,
  },
  {
    id: "pee",
    category: "body",
    icon: "🚻",
    en: "Need to pee",
    pa: "ਪਿਸ਼ਾਬ ਕਰਨਾ ਹੈ",
    speakEn: "I need to urinate.",
    speakPa: "ਮੈਨੂੰ ਪਿਸ਼ਾਬ ਕਰਨਾ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "nauseous",
    category: "body",
    icon: "🤢",
    en: "Nauseous",
    pa: "ਜੀ ਮਤਲਾ ਰਿਹਾ ਹੈ",
    speakEn: "I feel nauseous.",
    speakPa: "ਮੇਰਾ ਜੀ ਮਤਲਾ ਰਿਹਾ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "dizzy",
    category: "body",
    icon: "💫",
    en: "Dizzy",
    pa: "ਚੱਕਰ ਆ ਰਹੇ ਹਨ",
    speakEn: "I feel dizzy.",
    speakPa: "ਮੈਨੂੰ ਚੱਕਰ ਆ ਰਹੇ ਹਨ।",
    favorite: false,
    visible: true,
  },
  {
    id: "itchy",
    category: "body",
    icon: "🖐️",
    en: "Itchy",
    pa: "ਖੁਜਲੀ ਹੋ ਰਹੀ ਹੈ",
    speakEn: "I feel itchy.",
    speakPa: "ਮੈਨੂੰ ਖੁਜਲੀ ਹੋ ਰਹੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "pillow-up",
    category: "comfort",
    icon: "⬆️",
    en: "Pillow up",
    pa: "ਸਿਰਹਾਣਾ ਉੱਪਰ",
    speakEn: "Please move my pillow up.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰਾ ਸਿਰਹਾਣਾ ਉੱਪਰ ਕਰੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "pillow-down",
    category: "comfort",
    icon: "⬇️",
    en: "Pillow down",
    pa: "ਸਿਰਹਾਣਾ ਹੇਠਾਂ",
    speakEn: "Please move my pillow down.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰਾ ਸਿਰਹਾਣਾ ਹੇਠਾਂ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "leg-pillow",
    category: "comfort",
    icon: "🦵",
    en: "Adjust leg pillow",
    pa: "ਲੱਤ ਦਾ ਸਿਰਹਾਣਾ ਠੀਕ ਕਰੋ",
    speakEn: "Please adjust the pillow under my leg.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੀ ਲੱਤ ਹੇਠਲਾ ਸਿਰਹਾਣਾ ਠੀਕ ਕਰੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "turn-left",
    category: "comfort",
    icon: "↩️",
    en: "Turn me left",
    pa: "ਮੈਨੂੰ ਖੱਬੇ ਮੋੜੋ",
    speakEn: "Please turn me onto my left side.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਖੱਬੇ ਪਾਸੇ ਮੋੜੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "turn-right",
    category: "comfort",
    icon: "↪️",
    en: "Turn me right",
    pa: "ਮੈਨੂੰ ਸੱਜੇ ਮੋੜੋ",
    speakEn: "Please turn me onto my right side.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਸੱਜੇ ਪਾਸੇ ਮੋੜੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "sit-up",
    category: "comfort",
    icon: "🛏️",
    en: "Sit me up",
    pa: "ਮੈਨੂੰ ਉੱਪਰ ਬਿਠਾਓ",
    speakEn: "Please sit me up.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਉੱਪਰ ਬਿਠਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "lie-back",
    category: "comfort",
    icon: "😌",
    en: "Lay me back",
    pa: "ਮੈਨੂੰ ਪਿੱਛੇ ਲਿਟਾਓ",
    speakEn: "Please lay me back.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਪਿੱਛੇ ਲਿਟਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "curtain-open",
    category: "comfort",
    icon: "🌤️",
    en: "Open curtain",
    pa: "ਪਰਦਾ ਖੋਲ੍ਹੋ",
    speakEn: "Please open the curtain.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਪਰਦਾ ਖੋਲ੍ਹੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "curtain-close",
    category: "comfort",
    icon: "🌙",
    en: "Close curtain",
    pa: "ਪਰਦਾ ਬੰਦ ਕਰੋ",
    speakEn: "Please close the curtain.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਪਰਦਾ ਬੰਦ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "blanket-on",
    category: "comfort",
    icon: "🧣",
    en: "Blanket on",
    pa: "ਕੰਬਲ ਪਾਓ",
    speakEn: "Please put the blanket on me.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੇ ਉੱਤੇ ਕੰਬਲ ਪਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "blanket-off",
    category: "comfort",
    icon: "☀️",
    en: "Blanket off",
    pa: "ਕੰਬਲ ਹਟਾਓ",
    speakEn: "Please take the blanket off.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਕੰਬਲ ਹਟਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "too-hot",
    category: "comfort",
    icon: "🥵",
    en: "Too hot",
    pa: "ਬਹੁਤ ਗਰਮੀ ਹੈ",
    speakEn: "I am too hot.",
    speakPa: "ਮੈਨੂੰ ਬਹੁਤ ਗਰਮੀ ਲੱਗ ਰਹੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "too-cold",
    category: "comfort",
    icon: "🥶",
    en: "Too cold",
    pa: "ਬਹੁਤ ਠੰਢ ਹੈ",
    speakEn: "I am too cold.",
    speakPa: "ਮੈਨੂੰ ਬਹੁਤ ਠੰਢ ਲੱਗ ਰਹੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "eye-drops",
    category: "care",
    icon: "👁️",
    en: "Eye drops",
    pa: "ਅੱਖਾਂ ਦੀ ਦਵਾਈ",
    speakEn: "I need my eye drops.",
    speakPa: "ਮੈਨੂੰ ਅੱਖਾਂ ਦੀ ਦਵਾਈ ਚਾਹੀਦੀ ਹੈ।",
    favorite: true,
    visible: true,
  },
  {
    id: "hair-care",
    category: "care",
    icon: "🪮",
    en: "Fix my hair",
    pa: "ਮੇਰੇ ਵਾਲ ਸੰਵਾਰੋ",
    speakEn: "Please take care of my hair.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੇ ਵਾਲ ਸੰਵਾਰੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "medicine",
    category: "care",
    icon: "💊",
    en: "Medicine",
    pa: "ਦਵਾਈ",
    speakEn: "I need my medicine.",
    speakPa: "ਮੈਨੂੰ ਆਪਣੀ ਦਵਾਈ ਚਾਹੀਦੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "mouth-care",
    category: "care",
    icon: "🪥",
    en: "Mouth care",
    pa: "ਮੂੰਹ ਸਾਫ਼ ਕਰੋ",
    speakEn: "Please help clean my mouth.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰਾ ਮੂੰਹ ਸਾਫ਼ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "glasses",
    category: "care",
    icon: "👓",
    en: "My glasses",
    pa: "ਮੇਰੀ ਐਨਕ",
    speakEn: "Please bring me my glasses.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੀ ਐਨਕ ਲਿਆਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "paath",
    category: "activities",
    icon: "🙏",
    en: "Listen to Paath",
    pa: "ਪਾਠ ਸੁਣਨਾ ਹੈ",
    speakEn: "I would like to listen to Paath.",
    speakPa: "ਮੈਂ ਪਾਠ ਸੁਣਨਾ ਚਾਹੁੰਦੀ ਹਾਂ।",
    favorite: true,
    visible: true,
  },
  {
    id: "family",
    category: "activities",
    icon: "👨‍👩‍👧‍👦",
    en: "Call family",
    pa: "ਪਰਿਵਾਰ ਨੂੰ ਫ਼ੋਨ ਕਰੋ",
    speakEn: "Please call my family.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੇ ਪਰਿਵਾਰ ਨੂੰ ਫ਼ੋਨ ਕਰੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "music",
    category: "activities",
    icon: "🎵",
    en: "Play music",
    pa: "ਸੰਗੀਤ ਚਲਾਓ",
    speakEn: "I would like to listen to music.",
    speakPa: "ਮੈਂ ਸੰਗੀਤ ਸੁਣਨਾ ਚਾਹੁੰਦੀ ਹਾਂ।",
    favorite: false,
    visible: true,
  },
  {
    id: "tv",
    category: "activities",
    icon: "📺",
    en: "Television",
    pa: "ਟੀਵੀ ਚਲਾਓ",
    speakEn: "I would like to watch television.",
    speakPa: "ਮੈਂ ਟੀਵੀ ਦੇਖਣਾ ਚਾਹੁੰਦੀ ਹਾਂ।",
    favorite: false,
    visible: true,
  },
  {
    id: "lights-on",
    category: "activities",
    icon: "💡",
    en: "Lights on",
    pa: "ਬੱਤੀ ਜਗਾਓ",
    speakEn: "Please turn the lights on.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਬੱਤੀ ਜਗਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "lights-off",
    category: "activities",
    icon: "🌑",
    en: "Lights off",
    pa: "ਬੱਤੀ ਬੰਦ ਕਰੋ",
    speakEn: "Please turn the lights off.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਬੱਤੀ ਬੰਦ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
];

export const painLocations = [
  { icon: "🧠", en: "Head", pa: "ਸਿਰ", speakPa: "ਮੇਰੇ ਸਿਰ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "👁️", en: "Eye", pa: "ਅੱਖ", speakPa: "ਮੇਰੀ ਅੱਖ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🦷", en: "Mouth / teeth", pa: "ਮੂੰਹ / ਦੰਦ", speakPa: "ਮੇਰੇ ਮੂੰਹ ਜਾਂ ਦੰਦਾਂ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🫁", en: "Chest", pa: "ਛਾਤੀ", speakPa: "ਮੇਰੀ ਛਾਤੀ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🫄", en: "Stomach", pa: "ਢਿੱਡ", speakPa: "ਮੇਰੇ ਢਿੱਡ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🔙", en: "Back", pa: "ਪਿੱਠ", speakPa: "ਮੇਰੀ ਪਿੱਠ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "💪", en: "Arm / shoulder", pa: "ਬਾਂਹ / ਮੋਢਾ", speakPa: "ਮੇਰੀ ਬਾਂਹ ਜਾਂ ਮੋਢੇ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🖐️", en: "Hand", pa: "ਹੱਥ", speakPa: "ਮੇਰੇ ਹੱਥ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🦴", en: "Hip", pa: "ਚੂਲਾ", speakPa: "ਮੇਰੇ ਚੂਲੇ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🦵", en: "Leg / knee", pa: "ਲੱਤ / ਗੋਡਾ", speakPa: "ਮੇਰੀ ਲੱਤ ਜਾਂ ਗੋਡੇ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🦶", en: "Foot", pa: "ਪੈਰ", speakPa: "ਮੇਰੇ ਪੈਰ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🫶", en: "All over", pa: "ਸਾਰੇ ਸਰੀਰ ਵਿੱਚ", speakPa: "ਮੇਰੇ ਸਾਰੇ ਸਰੀਰ ਵਿੱਚ ਦਰਦ ਹੈ।" },
];

export const gurbaniQuotes = [
  {
    pa: "ਤੂੰ ਮੇਰਾ ਪਿਤਾ ਤੂੰਹੈ ਮੇਰਾ ਮਾਤਾ ॥",
    transliteration: "Too mera pita, too hai mera mata.",
    en: "You are my father; You are my mother.",
  },
  {
    pa: "ਮਨ ਜੀਤੈ ਜਗੁ ਜੀਤੁ ॥",
    transliteration: "Man jeetai jag jeet.",
    en: "Conquer your mind, and conquer the world.",
  },
  {
    pa: "ਤੇਰਾ ਕੀਆ ਮੀਠਾ ਲਾਗੈ ॥",
    transliteration: "Tera keeaa meetha laagai.",
    en: "Your will feels sweet to me.",
  },
  {
    pa: "ਸਭਨਾ ਜੀਆ ਕਾ ਇਕੁ ਦਾਤਾ ਸੋ ਮੈ ਵਿਸਰਿ ਨ ਜਾਈ ॥",
    transliteration: "Sabhna jeeaa ka ik daata, so mai visar na jaaee.",
    en: "There is one giver for all beings; may I never forget.",
  },
  {
    pa: "ਸਰਬ ਰੋਗ ਕਾ ਅਉਖਦੁ ਨਾਮੁ ॥",
    transliteration: "Sarab rog ka aukhadh naam.",
    en: "The Naam is the remedy for every illness.",
  },
];
