export const categories = [
  { id: "favorites", icon: "⭐", en: "Favorites", pa: "ਮਨਪਸੰਦ" },
  { id: "urgent", icon: "🆘", en: "Urgent", pa: "ਜ਼ਰੂਰੀ" },
  { id: "comfort", icon: "🛏️", en: "Comfort", pa: "ਆਰਾਮ" },
  { id: "body", icon: "🫶", en: "Body", pa: "ਸਰੀਰ" },
  { id: "food", icon: "🥣", en: "Food", pa: "ਖਾਣਾ" },
  { id: "care", icon: "🩺", en: "Care", pa: "ਦੇਖਭਾਲ" },
  { id: "communication", icon: "💬", en: "Talk", pa: "ਗੱਲਬਾਤ" },
  { id: "feelings", icon: "💛", en: "Feelings", pa: "ਭਾਵਨਾਵਾਂ" },
  { id: "activities", icon: "🎧", en: "More", pa: "ਹੋਰ" },
];

export const seedRequests = [
  {
    id: "nurse",
    category: "urgent",
    icon: "👩‍⚕️",
    en: "Call nurse",
    pa: "ਨਰਸ ਬੁਲਾਓ",
    speakEn: "Please call the nurse.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਨਰਸ ਨੂੰ ਬੁਲਾਓ।",
    favorite: true,
    visible: true,
    tone: "urgent",
  },
  {
    id: "help-now",
    category: "urgent",
    icon: "🆘",
    en: "Help now",
    pa: "ਹੁਣੇ ਮਦਦ",
    speakEn: "I need help right now.",
    speakPa: "ਮੈਨੂੰ ਹੁਣੇ ਮਦਦ ਚਾਹੀਦੀ ਹੈ।",
    favorite: true,
    visible: true,
    tone: "urgent",
  },
  {
    id: "breathing",
    category: "urgent",
    icon: "🫁",
    en: "Can't breathe",
    pa: "ਸਾਹ ਨਹੀਂ ਆ ਰਿਹਾ",
    speakEn: "I am having trouble breathing. Please help now.",
    speakPa: "ਮੈਨੂੰ ਸਾਹ ਲੈਣ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੋ ਰਹੀ ਹੈ। ਹੁਣੇ ਮਦਦ ਕਰੋ।",
    favorite: false,
    visible: true,
    tone: "urgent",
  },
  {
    id: "something-wrong",
    category: "urgent",
    icon: "⚠️",
    en: "Something is wrong",
    pa: "ਕੁਝ ਠੀਕ ਨਹੀਂ ਹੈ",
    speakEn: "Something feels wrong. Please check on me.",
    speakPa: "ਕੁਝ ਠੀਕ ਨਹੀਂ ਲੱਗ ਰਿਹਾ। ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਚੈੱਕ ਕਰੋ।",
    favorite: false,
    visible: true,
    tone: "urgent",
  },
  {
    id: "chest-pain",
    category: "urgent",
    icon: "💔",
    en: "Chest pain",
    pa: "ਛਾਤੀ ਵਿੱਚ ਦਰਦ",
    speakEn: "I have chest pain. Please help now.",
    speakPa: "ਮੇਰੀ ਛਾਤੀ ਵਿੱਚ ਦਰਦ ਹੈ। ਹੁਣੇ ਮਦਦ ਕਰੋ।",
    favorite: false,
    visible: true,
    tone: "urgent",
  },
  {
    id: "choking",
    category: "urgent",
    icon: "🫁",
    en: "Choking / coughing",
    pa: "ਖੰਘ ਜਾਂ ਸਾਹ ਰੁਕ ਰਿਹਾ",
    speakEn: "I am choking or coughing. Please help now.",
    speakPa: "ਮੈਨੂੰ ਖੰਘ ਆ ਰਹੀ ਹੈ ਜਾਂ ਸਾਹ ਰੁਕ ਰਿਹਾ ਹੈ। ਹੁਣੇ ਮਦਦ ਕਰੋ।",
    favorite: false,
    visible: true,
    tone: "urgent",
  },
  {
    id: "cant-swallow",
    category: "urgent",
    icon: "🚫",
    en: "Can't swallow",
    pa: "ਨਿਗਲ ਨਹੀਂ ਸਕਦੀ",
    speakEn: "I cannot swallow safely. Please help.",
    speakPa: "ਮੈਂ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਨਿਗਲ ਨਹੀਂ ਸਕਦੀ। ਕਿਰਪਾ ਕਰਕੇ ਮਦਦ ਕਰੋ।",
    favorite: false,
    visible: true,
    tone: "urgent",
  },
  {
    id: "pain",
    category: "body",
    icon: "🤕",
    en: "I am in pain",
    pa: "ਮੈਨੂੰ ਦਰਦ ਹੈ",
    speakEn: "I am in pain.",
    speakPa: "ਮੈਨੂੰ ਦਰਦ ਹੈ।",
    favorite: true,
    visible: true,
    tone: "pain",
    action: "pain",
  },
  {
    id: "yes",
    category: "favorites",
    icon: "👍",
    en: "Yes",
    pa: "ਹਾਂ",
    speakEn: "Yes.",
    speakPa: "ਹਾਂ।",
    favorite: true,
    visible: true,
    tone: "yes",
  },
  {
    id: "no",
    category: "favorites",
    icon: "👎",
    en: "No",
    pa: "ਨਹੀਂ",
    speakEn: "No.",
    speakPa: "ਨਹੀਂ।",
    favorite: true,
    visible: true,
    tone: "no",
  },
  {
    id: "stop",
    category: "communication",
    icon: "✋",
    en: "Stop",
    pa: "ਰੁਕੋ",
    speakEn: "Please stop.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਰੁਕੋ।",
    favorite: false,
    visible: true,
    tone: "urgent",
  },
  {
    id: "water",
    category: "food",
    icon: "💧",
    en: "Water",
    pa: "ਪਾਣੀ",
    speakEn: "I would like some water.",
    speakPa: "ਮੈਨੂੰ ਪਾਣੀ ਚਾਹੀਦਾ ਹੈ।",
    favorite: true,
    visible: true,
  },
  {
    id: "hungry",
    category: "food",
    icon: "🥣",
    en: "I am hungry",
    pa: "ਮੈਨੂੰ ਭੁੱਖ ਲੱਗੀ ਹੈ",
    speakEn: "I am hungry. I would like something to eat.",
    speakPa: "ਮੈਨੂੰ ਭੁੱਖ ਲੱਗੀ ਹੈ। ਮੈਨੂੰ ਕੁਝ ਖਾਣ ਲਈ ਚਾਹੀਦਾ ਹੈ।",
    favorite: true,
    visible: true,
  },
  {
    id: "tea",
    category: "food",
    icon: "☕",
    en: "Tea",
    pa: "ਚਾਹ",
    speakEn: "I would like some tea.",
    speakPa: "ਮੈਨੂੰ ਚਾਹ ਚਾਹੀਦੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "change-me",
    category: "body",
    icon: "🧷",
    en: "Change me",
    pa: "ਮੈਨੂੰ ਬਦਲੋ",
    speakEn: "I need to be changed, please.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਬਦਲੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "poop",
    category: "body",
    icon: "🚽",
    en: "Need to poop",
    pa: "ਪਖਾਨਾ ਜਾਣਾ ਹੈ",
    speakEn: "I need to have a bowel movement.",
    speakPa: "ਮੈਨੂੰ ਪਖਾਨਾ ਜਾਣਾ ਹੈ।",
    favorite: true,
    visible: true,
  },
  {
    id: "pee",
    category: "body",
    icon: "🚻",
    en: "Need to pee",
    pa: "ਪਿਸ਼ਾਬ ਕਰਨਾ ਹੈ",
    speakEn: "I need to urinate.",
    speakPa: "ਮੈਨੂੰ ਪਿਸ਼ਾਬ ਕਰਨਾ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "nauseous",
    category: "body",
    icon: "🤢",
    en: "Nauseous",
    pa: "ਜੀ ਮਤਲਾ ਰਿਹਾ ਹੈ",
    speakEn: "I feel nauseous.",
    speakPa: "ਮੇਰਾ ਜੀ ਮਤਲਾ ਰਿਹਾ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "dizzy",
    category: "body",
    icon: "💫",
    en: "Dizzy",
    pa: "ਚੱਕਰ ਆ ਰਹੇ ਹਨ",
    speakEn: "I feel dizzy.",
    speakPa: "ਮੈਨੂੰ ਚੱਕਰ ਆ ਰਹੇ ਹਨ।",
    favorite: false,
    visible: true,
  },
  {
    id: "itchy",
    category: "body",
    icon: "🖐️",
    en: "Itchy",
    pa: "ਖੁਜਲੀ ਹੋ ਰਹੀ ਹੈ",
    speakEn: "I feel itchy.",
    speakPa: "ਮੈਨੂੰ ਖੁਜਲੀ ਹੋ ਰਹੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "uncomfortable",
    category: "body",
    icon: "😖",
    en: "Uncomfortable",
    pa: "ਆਰਾਮ ਨਹੀਂ ਹੈ",
    speakEn: "I am uncomfortable, but I am not sure why.",
    speakPa: "ਮੈਨੂੰ ਆਰਾਮ ਨਹੀਂ ਹੈ, ਪਰ ਮੈਨੂੰ ਪਤਾ ਨਹੀਂ ਕਿਉਂ।",
    favorite: false,
    visible: true,
  },
  {
    id: "dry-mouth",
    category: "body",
    icon: "👄",
    en: "Dry mouth",
    pa: "ਮੂੰਹ ਸੁੱਕ ਰਿਹਾ ਹੈ",
    speakEn: "My mouth feels dry. Please help with mouth care.",
    speakPa: "ਮੇਰਾ ਮੂੰਹ ਸੁੱਕ ਰਿਹਾ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਮੂੰਹ ਦੀ ਦੇਖਭਾਲ ਵਿੱਚ ਮਦਦ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "pillow-up",
    category: "comfort",
    icon: "⬆️",
    en: "Pillow up",
    pa: "ਸਿਰਹਾਣਾ ਉੱਪਰ",
    speakEn: "Please move my pillow up.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰਾ ਸਿਰਹਾਣਾ ਉੱਪਰ ਕਰੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "pillow-down",
    category: "comfort",
    icon: "⬇️",
    en: "Pillow down",
    pa: "ਸਿਰਹਾਣਾ ਹੇਠਾਂ",
    speakEn: "Please move my pillow down.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰਾ ਸਿਰਹਾਣਾ ਹੇਠਾਂ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "bed-up",
    category: "comfort",
    icon: "⏫",
    en: "Raise bed",
    pa: "ਬਿਸਤਰਾ ਉੱਪਰ ਕਰੋ",
    speakEn: "Please raise my bed.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰਾ ਬਿਸਤਰਾ ਉੱਪਰ ਕਰੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "bed-down",
    category: "comfort",
    icon: "⏬",
    en: "Lower bed",
    pa: "ਬਿਸਤਰਾ ਹੇਠਾਂ ਕਰੋ",
    speakEn: "Please lower my bed.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰਾ ਬਿਸਤਰਾ ਹੇਠਾਂ ਕਰੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "leg-pillow",
    category: "comfort",
    icon: "🦵",
    en: "Adjust leg pillow",
    pa: "ਲੱਤ ਦਾ ਸਿਰਹਾਣਾ ਠੀਕ ਕਰੋ",
    speakEn: "Please adjust the pillow under my leg.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੀ ਲੱਤ ਹੇਠਲਾ ਸਿਰਹਾਣਾ ਠੀਕ ਕਰੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "turn-left",
    category: "comfort",
    icon: "↩️",
    en: "Turn me left",
    pa: "ਮੈਨੂੰ ਖੱਬੇ ਮੋੜੋ",
    speakEn: "Please turn me onto my left side.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਖੱਬੇ ਪਾਸੇ ਮੋੜੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "turn-right",
    category: "comfort",
    icon: "↪️",
    en: "Turn me right",
    pa: "ਮੈਨੂੰ ਸੱਜੇ ਮੋੜੋ",
    speakEn: "Please turn me onto my right side.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਸੱਜੇ ਪਾਸੇ ਮੋੜੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "sit-up",
    category: "comfort",
    icon: "🛏️",
    en: "Sit me up",
    pa: "ਮੈਨੂੰ ਉੱਪਰ ਬਿਠਾਓ",
    speakEn: "Please sit me up.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਉੱਪਰ ਬਿਠਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "lie-back",
    category: "comfort",
    icon: "😌",
    en: "Lay me back",
    pa: "ਮੈਨੂੰ ਪਿੱਛੇ ਲਿਟਾਓ",
    speakEn: "Please lay me back.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਪਿੱਛੇ ਲਿਟਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "curtain-open",
    category: "comfort",
    icon: "🌤️",
    en: "Open curtain",
    pa: "ਪਰਦਾ ਖੋਲ੍ਹੋ",
    speakEn: "Please open the curtain.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਪਰਦਾ ਖੋਲ੍ਹੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "curtain-close",
    category: "comfort",
    icon: "🌙",
    en: "Close curtain",
    pa: "ਪਰਦਾ ਬੰਦ ਕਰੋ",
    speakEn: "Please close the curtain.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਪਰਦਾ ਬੰਦ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "blanket-on",
    category: "comfort",
    icon: "🧣",
    en: "Blanket on",
    pa: "ਕੰਬਲ ਪਾਓ",
    speakEn: "Please put the blanket on me.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੇ ਉੱਤੇ ਕੰਬਲ ਪਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "blanket-off",
    category: "comfort",
    icon: "☀️",
    en: "Blanket off",
    pa: "ਕੰਬਲ ਹਟਾਓ",
    speakEn: "Please take the blanket off.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਕੰਬਲ ਹਟਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "too-hot",
    category: "comfort",
    icon: "🥵",
    en: "Too hot",
    pa: "ਬਹੁਤ ਗਰਮੀ ਹੈ",
    speakEn: "I am too hot.",
    speakPa: "ਮੈਨੂੰ ਬਹੁਤ ਗਰਮੀ ਲੱਗ ਰਹੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "too-cold",
    category: "comfort",
    icon: "🥶",
    en: "Too cold",
    pa: "ਬਹੁਤ ਠੰਢ ਹੈ",
    speakEn: "I am too cold.",
    speakPa: "ਮੈਨੂੰ ਬਹੁਤ ਠੰਢ ਲੱਗ ਰਹੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "adjust-arm",
    category: "comfort",
    icon: "💪",
    en: "Adjust my arm",
    pa: "ਮੇਰੀ ਬਾਂਹ ਠੀਕ ਕਰੋ",
    speakEn: "Please adjust and support my arm.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੀ ਬਾਂਹ ਨੂੰ ਠੀਕ ਕਰਕੇ ਸਹਾਰਾ ਦਿਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "sliding-down",
    category: "comfort",
    icon: "🛝",
    en: "I am sliding down",
    pa: "ਮੈਂ ਹੇਠਾਂ ਖਿਸਕ ਰਹੀ ਹਾਂ",
    speakEn: "I am sliding down in the bed. Please reposition me.",
    speakPa: "ਮੈਂ ਬਿਸਤਰੇ ਵਿੱਚ ਹੇਠਾਂ ਖਿਸਕ ਰਹੀ ਹਾਂ। ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਠੀਕ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "privacy",
    category: "comfort",
    icon: "🔒",
    en: "I need privacy",
    pa: "ਮੈਨੂੰ ਇਕਾਂਤ ਚਾਹੀਦਾ ਹੈ",
    speakEn: "I need privacy, please.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਇਕਾਂਤ ਚਾਹੀਦਾ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "too-loud",
    category: "comfort",
    icon: "🔇",
    en: "Too loud",
    pa: "ਬਹੁਤ ਸ਼ੋਰ ਹੈ",
    speakEn: "It is too loud. Please make it quieter.",
    speakPa: "ਬਹੁਤ ਸ਼ੋਰ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਆਵਾਜ਼ ਘੱਟ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "eye-drops",
    category: "care",
    icon: "👁️",
    en: "Eye drops",
    pa: "ਅੱਖਾਂ ਦੀ ਦਵਾਈ",
    speakEn: "I need my eye drops.",
    speakPa: "ਮੈਨੂੰ ਅੱਖਾਂ ਦੀ ਦਵਾਈ ਚਾਹੀਦੀ ਹੈ।",
    favorite: true,
    visible: true,
  },
  {
    id: "hair-care",
    category: "care",
    icon: "🪮",
    en: "Fix my hair",
    pa: "ਮੇਰੇ ਵਾਲ ਸੰਵਾਰੋ",
    speakEn: "Please take care of my hair.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੇ ਵਾਲ ਸੰਵਾਰੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "medicine",
    category: "care",
    icon: "💊",
    en: "Medicine",
    pa: "ਦਵਾਈ",
    speakEn: "I need my medicine.",
    speakPa: "ਮੈਨੂੰ ਆਪਣੀ ਦਵਾਈ ਚਾਹੀਦੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "mouth-care",
    category: "care",
    icon: "🪥",
    en: "Mouth care",
    pa: "ਮੂੰਹ ਸਾਫ਼ ਕਰੋ",
    speakEn: "Please help clean my mouth.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰਾ ਮੂੰਹ ਸਾਫ਼ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "glasses",
    category: "care",
    icon: "👓",
    en: "My glasses",
    pa: "ਮੇਰੀ ਐਨਕ",
    speakEn: "Please bring me my glasses.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੀ ਐਨਕ ਲਿਆਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "hearing-aid",
    category: "care",
    icon: "🦻",
    en: "Hearing aid",
    pa: "ਸੁਣਨ ਵਾਲੀ ਮਸ਼ੀਨ",
    speakEn: "Please check and adjust my hearing aid.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੀ ਸੁਣਨ ਵਾਲੀ ਮਸ਼ੀਨ ਚੈੱਕ ਕਰਕੇ ਠੀਕ ਕਰੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "clean-face",
    category: "care",
    icon: "🧼",
    en: "Clean my face",
    pa: "ਮੇਰਾ ਮੂੰਹ ਸਾਫ਼ ਕਰੋ",
    speakEn: "Please help clean my face.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰਾ ਚਿਹਰਾ ਸਾਫ਼ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "wash-hands",
    category: "care",
    icon: "🫧",
    en: "Wash my hands",
    pa: "ਮੇਰੇ ਹੱਥ ਧੋਵੋ",
    speakEn: "Please help wash my hands.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੇ ਹੱਥ ਧੋਣ ਵਿੱਚ ਮਦਦ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "lip-balm",
    category: "care",
    icon: "💄",
    en: "Lip balm",
    pa: "ਬੁੱਲ੍ਹਾਂ ਲਈ ਬਾਮ",
    speakEn: "Please put lip balm on my lips.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੇ ਬੁੱਲ੍ਹਾਂ ਉੱਤੇ ਬਾਮ ਲਗਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "bath",
    category: "care",
    icon: "🛁",
    en: "Wash / bath",
    pa: "ਨਹਾਉਣਾ ਹੈ",
    speakEn: "I would like help washing or bathing.",
    speakPa: "ਮੈਨੂੰ ਨਹਾਉਣ ਜਾਂ ਸਾਫ਼ ਹੋਣ ਵਿੱਚ ਮਦਦ ਚਾਹੀਦੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "give-time",
    category: "communication",
    icon: "⏳",
    en: "Give me time",
    pa: "ਮੈਨੂੰ ਸਮਾਂ ਦਿਓ",
    speakEn: "Please give me more time to respond.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਜਵਾਬ ਦੇਣ ਲਈ ਹੋਰ ਸਮਾਂ ਦਿਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "ask-yes-no",
    category: "communication",
    icon: "❓",
    en: "Ask yes / no",
    pa: "ਹਾਂ ਜਾਂ ਨਹੀਂ ਪੁੱਛੋ",
    speakEn: "Please ask me one yes or no question at a time.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਇੱਕ ਵਾਰ ਵਿੱਚ ਇੱਕ ਹਾਂ ਜਾਂ ਨਹੀਂ ਵਾਲਾ ਸਵਾਲ ਪੁੱਛੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "dont-understand",
    category: "communication",
    icon: "🤷",
    en: "I don't understand",
    pa: "ਮੈਨੂੰ ਸਮਝ ਨਹੀਂ ਆਈ",
    speakEn: "I do not understand.",
    speakPa: "ਮੈਨੂੰ ਸਮਝ ਨਹੀਂ ਆਈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "please-explain",
    category: "communication",
    icon: "🗣️",
    en: "Please explain",
    pa: "ਕਿਰਪਾ ਕਰਕੇ ਸਮਝਾਓ",
    speakEn: "Please explain that slowly and simply.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਹੌਲੀ ਅਤੇ ਸੌਖੇ ਤਰੀਕੇ ਨਾਲ ਸਮਝਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "not-what-i-mean",
    category: "communication",
    icon: "🔄",
    en: "Not what I mean",
    pa: "ਮੇਰਾ ਇਹ ਮਤਲਬ ਨਹੀਂ",
    speakEn: "That is not what I mean. Please try again.",
    speakPa: "ਮੇਰਾ ਇਹ ਮਤਲਬ ਨਹੀਂ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "finished",
    category: "communication",
    icon: "✅",
    en: "I am finished",
    pa: "ਮੈਂ ਪੂਰਾ ਕਰ ਲਿਆ",
    speakEn: "I am finished. Thank you.",
    speakPa: "ਮੈਂ ਪੂਰਾ ਕਰ ਲਿਆ ਹੈ। ਧੰਨਵਾਦ।",
    favorite: false,
    visible: true,
  },
  {
    id: "more",
    category: "communication",
    icon: "➕",
    en: "More",
    pa: "ਹੋਰ",
    speakEn: "I would like more, please.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਹੋਰ ਚਾਹੀਦਾ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "less",
    category: "communication",
    icon: "➖",
    en: "Less",
    pa: "ਘੱਟ",
    speakEn: "I would like less, please.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਘੱਟ ਚਾਹੀਦਾ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "scared",
    category: "feelings",
    icon: "😟",
    en: "I am scared",
    pa: "ਮੈਨੂੰ ਡਰ ਲੱਗ ਰਿਹਾ ਹੈ",
    speakEn: "I feel scared. Please stay with me.",
    speakPa: "ਮੈਨੂੰ ਡਰ ਲੱਗ ਰਿਹਾ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੇ ਕੋਲ ਰਹੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "sad",
    category: "feelings",
    icon: "😢",
    en: "I feel sad",
    pa: "ਮੈਂ ਉਦਾਸ ਹਾਂ",
    speakEn: "I feel sad.",
    speakPa: "ਮੈਂ ਉਦਾਸ ਹਾਂ।",
    favorite: false,
    visible: true,
  },
  {
    id: "tired",
    category: "feelings",
    icon: "😴",
    en: "I am tired",
    pa: "ਮੈਂ ਥੱਕ ਗਈ ਹਾਂ",
    speakEn: "I am tired and would like to rest.",
    speakPa: "ਮੈਂ ਥੱਕ ਗਈ ਹਾਂ ਅਤੇ ਆਰਾਮ ਕਰਨਾ ਚਾਹੁੰਦੀ ਹਾਂ।",
    favorite: false,
    visible: true,
  },
  {
    id: "stay-with-me",
    category: "feelings",
    icon: "🤝",
    en: "Please stay",
    pa: "ਮੇਰੇ ਕੋਲ ਰਹੋ",
    speakEn: "Please stay with me for a while.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਕੁਝ ਸਮਾਂ ਮੇਰੇ ਕੋਲ ਰਹੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "hold-my-hand",
    category: "feelings",
    icon: "🫱🏻‍🫲🏽",
    en: "Hold my hand",
    pa: "ਮੇਰਾ ਹੱਥ ਫੜੋ",
    speakEn: "Please hold my hand.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰਾ ਹੱਥ ਫੜੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "miss-you",
    category: "feelings",
    icon: "💞",
    en: "I miss you",
    pa: "ਮੈਨੂੰ ਤੁਹਾਡੀ ਯਾਦ ਆਉਂਦੀ ਹੈ",
    speakEn: "I miss you.",
    speakPa: "ਮੈਨੂੰ ਤੁਹਾਡੀ ਯਾਦ ਆਉਂਦੀ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "alone",
    category: "feelings",
    icon: "🕊️",
    en: "Want to be alone",
    pa: "ਮੈਂ ਇਕੱਲੀ ਰਹਿਣਾ ਚਾਹੁੰਦੀ ਹਾਂ",
    speakEn: "I would like to be alone for a while.",
    speakPa: "ਮੈਂ ਕੁਝ ਸਮਾਂ ਇਕੱਲੀ ਰਹਿਣਾ ਚਾਹੁੰਦੀ ਹਾਂ।",
    favorite: false,
    visible: true,
  },
  {
    id: "thank-you",
    category: "feelings",
    icon: "🙏",
    en: "Thank you",
    pa: "ਧੰਨਵਾਦ",
    speakEn: "Thank you.",
    speakPa: "ਧੰਨਵਾਦ।",
    favorite: false,
    visible: true,
  },
  {
    id: "love-you",
    category: "feelings",
    icon: "❤️",
    en: "I love you",
    pa: "ਮੈਂ ਤੁਹਾਨੂੰ ਪਿਆਰ ਕਰਦੀ ਹਾਂ",
    speakEn: "I love you.",
    speakPa: "ਮੈਂ ਤੁਹਾਨੂੰ ਪਿਆਰ ਕਰਦੀ ਹਾਂ।",
    favorite: false,
    visible: true,
  },
  {
    id: "family-coming",
    category: "feelings",
    icon: "🗓️",
    en: "When is family coming?",
    pa: "ਪਰਿਵਾਰ ਕਦੋਂ ਆਵੇਗਾ?",
    speakEn: "When is my family coming to visit?",
    speakPa: "ਮੇਰਾ ਪਰਿਵਾਰ ਮੈਨੂੰ ਮਿਲਣ ਕਦੋਂ ਆਵੇਗਾ?",
    favorite: false,
    visible: true,
  },
  {
    id: "paath",
    category: "activities",
    icon: "🙏",
    en: "Listen to Paath",
    pa: "ਪਾਠ ਸੁਣਨਾ ਹੈ",
    speakEn: "I would like to listen to Paath.",
    speakPa: "ਮੈਂ ਪਾਠ ਸੁਣਨਾ ਚਾਹੁੰਦੀ ਹਾਂ।",
    favorite: true,
    visible: true,
  },
  {
    id: "family",
    category: "activities",
    icon: "👨‍👩‍👧‍👦",
    en: "Call family",
    pa: "ਪਰਿਵਾਰ ਨੂੰ ਫ਼ੋਨ ਕਰੋ",
    speakEn: "Please call my family.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੇ ਪਰਿਵਾਰ ਨੂੰ ਫ਼ੋਨ ਕਰੋ।",
    favorite: true,
    visible: true,
  },
  {
    id: "music",
    category: "activities",
    icon: "🎵",
    en: "Play music",
    pa: "ਸੰਗੀਤ ਚਲਾਓ",
    speakEn: "I would like to listen to music.",
    speakPa: "ਮੈਂ ਸੰਗੀਤ ਸੁਣਨਾ ਚਾਹੁੰਦੀ ਹਾਂ।",
    favorite: false,
    visible: true,
  },
  {
    id: "tv-on",
    category: "activities",
    icon: "📺",
    en: "Turn TV on",
    pa: "ਟੀਵੀ ਚਲਾਓ",
    speakEn: "Please turn the television on.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਟੀਵੀ ਚਲਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "tv-off",
    category: "activities",
    icon: "📴",
    en: "Turn TV off",
    pa: "ਟੀਵੀ ਬੰਦ ਕਰੋ",
    speakEn: "Please turn the television off.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਟੀਵੀ ਬੰਦ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "tv-volume-up",
    category: "activities",
    icon: "🔊",
    en: "TV louder",
    pa: "ਟੀਵੀ ਦੀ ਆਵਾਜ਼ ਵਧਾਓ",
    speakEn: "Please make the television louder.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਟੀਵੀ ਦੀ ਆਵਾਜ਼ ਵਧਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "tv-volume-down",
    category: "activities",
    icon: "🔉",
    en: "TV quieter",
    pa: "ਟੀਵੀ ਦੀ ਆਵਾਜ਼ ਘਟਾਓ",
    speakEn: "Please make the television quieter.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਟੀਵੀ ਦੀ ਆਵਾਜ਼ ਘਟਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "tv-channel",
    category: "activities",
    icon: "⏭️",
    en: "Change channel",
    pa: "ਚੈਨਲ ਬਦਲੋ",
    speakEn: "Please change the television channel.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਟੀਵੀ ਦਾ ਚੈਨਲ ਬਦਲੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "video-call",
    category: "activities",
    icon: "📱",
    en: "Video call family",
    pa: "ਪਰਿਵਾਰ ਨਾਲ ਵੀਡੀਓ ਕਾਲ",
    speakEn: "Please help me make a video call with my family.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੇ ਪਰਿਵਾਰ ਨਾਲ ਵੀਡੀਓ ਕਾਲ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
  {
    id: "what-time",
    category: "activities",
    icon: "🕰️",
    en: "What time is it?",
    pa: "ਕਿੰਨੇ ਵਜੇ ਹਨ?",
    speakEn: "Please tell me what time it is.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਦੱਸੋ ਕਿ ਕਿੰਨੇ ਵਜੇ ਹਨ।",
    favorite: false,
    visible: true,
  },
  {
    id: "what-day",
    category: "activities",
    icon: "📅",
    en: "What day is it?",
    pa: "ਅੱਜ ਕਿਹੜਾ ਦਿਨ ਹੈ?",
    speakEn: "Please tell me what day it is.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਦੱਸੋ ਕਿ ਅੱਜ ਕਿਹੜਾ ਦਿਨ ਹੈ।",
    favorite: false,
    visible: true,
  },
  {
    id: "lights-on",
    category: "activities",
    icon: "💡",
    en: "Lights on",
    pa: "ਬੱਤੀ ਜਗਾਓ",
    speakEn: "Please turn the lights on.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਬੱਤੀ ਜਗਾਓ।",
    favorite: false,
    visible: true,
  },
  {
    id: "lights-off",
    category: "activities",
    icon: "🌑",
    en: "Lights off",
    pa: "ਬੱਤੀ ਬੰਦ ਕਰੋ",
    speakEn: "Please turn the lights off.",
    speakPa: "ਕਿਰਪਾ ਕਰਕੇ ਬੱਤੀ ਬੰਦ ਕਰੋ।",
    favorite: false,
    visible: true,
  },
];

export const painLocations = [
  { icon: "🧠", en: "Head", pa: "ਸਿਰ", speakPa: "ਮੇਰੇ ਸਿਰ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "👁️", en: "Eye", pa: "ਅੱਖ", speakPa: "ਮੇਰੀ ਅੱਖ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🦷", en: "Mouth / teeth", pa: "ਮੂੰਹ / ਦੰਦ", speakPa: "ਮੇਰੇ ਮੂੰਹ ਜਾਂ ਦੰਦਾਂ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🫁", en: "Chest", pa: "ਛਾਤੀ", speakPa: "ਮੇਰੀ ਛਾਤੀ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🫄", en: "Stomach", pa: "ਢਿੱਡ", speakPa: "ਮੇਰੇ ਢਿੱਡ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🔙", en: "Back", pa: "ਪਿੱਠ", speakPa: "ਮੇਰੀ ਪਿੱਠ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "💪", en: "Arm / shoulder", pa: "ਬਾਂਹ / ਮੋਢਾ", speakPa: "ਮੇਰੀ ਬਾਂਹ ਜਾਂ ਮੋਢੇ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🖐️", en: "Hand", pa: "ਹੱਥ", speakPa: "ਮੇਰੇ ਹੱਥ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🦴", en: "Hip", pa: "ਚੂਲਾ", speakPa: "ਮੇਰੇ ਚੂਲੇ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🦵", en: "Leg / knee", pa: "ਲੱਤ / ਗੋਡਾ", speakPa: "ਮੇਰੀ ਲੱਤ ਜਾਂ ਗੋਡੇ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🦶", en: "Foot", pa: "ਪੈਰ", speakPa: "ਮੇਰੇ ਪੈਰ ਵਿੱਚ ਦਰਦ ਹੈ।" },
  { icon: "🫶", en: "All over", pa: "ਸਾਰੇ ਸਰੀਰ ਵਿੱਚ", speakPa: "ਮੇਰੇ ਸਾਰੇ ਸਰੀਰ ਵਿੱਚ ਦਰਦ ਹੈ।" },
];

export const gurbaniQuotes = [
  {
    pa: "ਤੂੰ ਮੇਰਾ ਪਿਤਾ ਤੂੰਹੈ ਮੇਰਾ ਮਾਤਾ ॥",
    transliteration: "Too mera pita, too hai mera mata.",
    en: "You are my father; You are my mother.",
  },
  {
    pa: "ਮਨ ਜੀਤੈ ਜਗੁ ਜੀਤੁ ॥",
    transliteration: "Man jeetai jag jeet.",
    en: "Conquer your mind, and conquer the world.",
  },
  {
    pa: "ਤੇਰਾ ਕੀਆ ਮੀਠਾ ਲਾਗੈ ॥",
    transliteration: "Tera keeaa meetha laagai.",
    en: "Your will feels sweet to me.",
  },
  {
    pa: "ਸਭਨਾ ਜੀਆ ਕਾ ਇਕੁ ਦਾਤਾ ਸੋ ਮੈ ਵਿਸਰਿ ਨ ਜਾਈ ॥",
    transliteration: "Sabhna jeeaa ka ik daata, so mai visar na jaaee.",
    en: "There is one giver for all beings; may I never forget.",
  },
  {
    pa: "ਸਰਬ ਰੋਗ ਕਾ ਅਉਖਦੁ ਨਾਮੁ ॥",
    transliteration: "Sarab rog ka aukhadh naam.",
    en: "The Naam is the remedy for every illness.",
  },
];
